create extension if not exists vector;
create type public.risk_level as enum ('read','write','external','sensitive');
create type public.job_status as enum ('queued','running','completed','failed','cancelled');
create table public.profiles(id uuid primary key references auth.users on delete cascade, display_name text, class_level text default '12', board text default 'CBSE', created_at timestamptz default now());
create table public.subjects(id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, color text);
create table public.chapters(id uuid primary key default gen_random_uuid(), subject_id uuid references public.subjects on delete cascade, title text not null, position int not null, unique(subject_id,position));
create table public.topics(id uuid primary key default gen_random_uuid(), chapter_id uuid references public.chapters on delete cascade, title text not null, position int not null);
create table public.topic_progress(user_id uuid references auth.users on delete cascade, topic_id uuid references public.topics on delete cascade, status text default 'not_started', confidence smallint default 0 check(confidence between 0 and 100), updated_at timestamptz default now(), primary key(user_id,topic_id));
create table public.conversations(id uuid primary key default gen_random_uuid(), user_id uuid references auth.users on delete cascade, title text, created_at timestamptz default now());
create table public.messages(id uuid primary key default gen_random_uuid(), conversation_id uuid references public.conversations on delete cascade, role text not null check(role in('user','assistant','tool')), content jsonb not null, created_at timestamptz default now());
create table public.action_plans(id uuid primary key default gen_random_uuid(), user_id uuid references auth.users on delete cascade, title text not null, summary text, steps jsonb not null default '[]', risk public.risk_level not null, status text default 'proposed', created_at timestamptz default now());
create table public.jobs(id uuid primary key default gen_random_uuid(), user_id uuid references auth.users on delete cascade, kind text not null, status public.job_status default 'queued', payload jsonb default '{}', result jsonb, progress smallint default 0, lease_until timestamptz, attempts int default 0, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.files(id uuid primary key default gen_random_uuid(), user_id uuid references auth.users on delete cascade, storage_path text not null, name text not null, mime_type text, sha256 text, source_url text, metadata jsonb default '{}', created_at timestamptz default now());
create table public.audit_events(id bigint generated always as identity primary key, user_id uuid references auth.users on delete cascade, action text not null, risk public.risk_level not null, input_redacted jsonb, result_redacted jsonb, created_at timestamptz default now());
alter table public.profiles enable row level security; alter table public.topic_progress enable row level security; alter table public.conversations enable row level security; alter table public.messages enable row level security; alter table public.action_plans enable row level security; alter table public.jobs enable row level security; alter table public.files enable row level security; alter table public.audit_events enable row level security;
create policy "own profile" on public.profiles for all using(auth.uid()=id) with check(auth.uid()=id);
create policy "own progress" on public.topic_progress for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own conversations" on public.conversations for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own plans" on public.action_plans for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own jobs" on public.jobs for select using(auth.uid()=user_id);
create policy "own files" on public.files for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own audit" on public.audit_events for select using(auth.uid()=user_id);
create policy "conversation messages" on public.messages for all using(exists(select 1 from public.conversations c where c.id=conversation_id and c.user_id=auth.uid())) with check(exists(select 1 from public.conversations c where c.id=conversation_id and c.user_id=auth.uid()));
