-- Closed learning loop: summaries, user-model conclusions, nudges and Agent Skills drafts.
create table if not exists public.session_summaries(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,conversation_id uuid not null references public.conversations on delete cascade,summary text not null,topics text[] not null default '{}',message_count int not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,conversation_id));
create table if not exists public.user_model_conclusions(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,subject text not null,predicate text not null,value jsonb not null,evidence jsonb not null default '[]',confidence real not null check(confidence between 0 and 1),status text not null default 'proposed' check(status in('proposed','accepted','rejected','superseded')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.nudges(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,kind text not null,title text not null,body text not null,evidence jsonb not null default '{}',status text not null default 'pending' check(status in('pending','shown','accepted','dismissed')),due_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.skills(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,name text not null,description text not null,instructions text not null,allowed_capabilities text[] not null default '{}',version int not null default 1,status text not null default 'draft' check(status in('draft','active','archived')),source_plan_id uuid references public.action_plans on delete set null,parent_skill_id uuid references public.skills on delete set null,package_manifest jsonb not null default '{}',metrics jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,name,version));
create table if not exists public.learning_observations(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,conversation_id uuid references public.conversations on delete cascade,kind text not null,content text not null,evidence jsonb not null default '[]',created_at timestamptz not null default now());
create table if not exists public.skill_outcomes(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,skill_id uuid not null references public.skills on delete cascade,run_id uuid,success boolean not null,score real check(score between 0 and 1),evidence jsonb not null default '{}',created_at timestamptz not null default now());
create index if not exists messages_fts_idx on public.messages using gin(to_tsvector('english',coalesce(content::text,'')));
create index if not exists summaries_fts_idx on public.session_summaries using gin(to_tsvector('english',summary));
create or replace function public.search_session_messages(uid uuid,query text,result_limit int default 20) returns table(conversation_id uuid,role text,content text,created_at timestamptz,score real,source text) language sql stable security invoker set search_path=public as $$
 select x.conversation_id,x.role,x.content,x.created_at,x.score,x.source from (
  select m.conversation_id,m.role,m.content::text content,m.created_at,ts_rank(to_tsvector('english',coalesce(m.content::text,'')),websearch_to_tsquery('english',query))::real score,'message'::text source from public.messages m join public.conversations c on c.id=m.conversation_id where c.user_id=uid and to_tsvector('english',coalesce(m.content::text,'')) @@ websearch_to_tsquery('english',query)
  union all
  select s.conversation_id,'summary'::text,s.summary,s.updated_at,ts_rank(to_tsvector('english',s.summary),websearch_to_tsquery('english',query))::real,'summary'::text from public.session_summaries s where s.user_id=uid and to_tsvector('english',s.summary) @@ websearch_to_tsquery('english',query)
 ) x order by x.score desc limit greatest(1,least(result_limit,100)) $$;

alter table public.session_summaries enable row level security;alter table public.user_model_conclusions enable row level security;alter table public.nudges enable row level security;alter table public.skills enable row level security;alter table public.learning_observations enable row level security;alter table public.skill_outcomes enable row level security;
create policy "own summaries" on public.session_summaries for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own conclusions" on public.user_model_conclusions for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own nudges" on public.nudges for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own skills" on public.skills for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own observations" on public.learning_observations for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own skill outcomes" on public.skill_outcomes for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
